### ISSUE TITLE
Exercise API

### ISSUE THREAD

**Issue by Soulful0** [Soulful0/Gym-Website#2]
# Exercise API

## User Story
As a user, 
I want the modal to show me a list of exercises sourced from a public fitness API,
so that I can learn more info aboutdifferent exercises

## Acceptance Criteria
GIVEN the need to have user select different exercises
WHEN a gym sign up application is used 
THEN use the following api, {insert API name here } to select the exercises.

**Comment by BlackHacwk** [comment]
Completed
