### ISSUE TITLE
Available Trainer Modal

### ISSUE THREAD

**Issue by Soulful0** [Soulful0/Gym-Website#3]
# Available Trainer Modal

## User Story
As a user, 
I want a modal to display available trainers, along with their specialties and contact information,
so that when I click on "more info", a list of available trainers is displayed

## Acceptance Criteria
GIVEN a gym website 
When I click on 'more info' button,
THEN I can see a list of available trainers, along with their specialties and contact information. I can pick and choose a specific trainer based on my need.

**Comment by scottchen2012** [comment]
Completed Available Trainer Modal
